# Generated by Django 5.1.3 on 2024-11-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_todo_due_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="completed",
        ),
        migrations.AddField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[("Todo", "todo"), ("Ongoing", "ongoing"), ("Done", "done")],
                default="Todo",
                max_length=9,
            ),
        ),
    ]
